leftnav:
- identifier: 511b29ee-4ef7-afe6-d23d-0c59929b24d1
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 10
- identifier: external-00cd3550d8bc4b2d95f5439e0c057e11
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:OCW+Pre-7.01+1T2020/about
  weight: 1000
